version: '3.8'

services:
  mysql-dev:
    image: mysql:8.0
    container_name: coffeeplz-mysql-dev
    environment:
      MYSQL_DATABASE: coffeeplz_dev
      MYSQL_USER: coffeeplz
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coffeeplz-dev-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app-dev:
    build:
      context: .
      target: runtime
    container_name: coffeeplz-app-dev
    depends_on:
      - mysql-dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: mysql-dev
      DB_PORT: 3306
      DB_NAME: coffeeplz_dev
      DB_USERNAME: coffeeplz
      DB_PASSWORD: password
      JWT_SECRET: dev-secret-key-12345678901234567890123456789012345678901234567890
      SWAGGER_ENABLED: true
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - coffeeplz-dev-network
    restart: unless-stopped

  # Optional: Redis for caching in development
  redis-dev:
    image: redis:7-alpine
    container_name: coffeeplz-redis-dev
    ports:
      - "6379:6379"
    networks:
      - coffeeplz-dev-network

volumes:
  mysql_dev_data:

networks:
  coffeeplz-dev-network:
    driver: bridge 