spring:
  datasource:
    url: jdbc:mysql://localhost:3307/coffeeplz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:coffeeplz}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.coffeeplz: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN 