spring:
  profiles:
    active: dev
  application:
    name: coffeeplz

server:
  port: 8080

logging:
  level:
    com.coffeeplz: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 